<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <RootNamespace>AddinManager.Gallery.WpfUi</RootNamespace>
    <AssemblyName>AddinManager.Gallery.WpfUi</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" />
  </ItemGroup>

</Project>
